CREATE TABLE [dbo].[Tickets]
(
	[Id] INT NOT NULL IDENTITY(1,1), 
    [Email] NVARCHAR(250) NOT NULL, 
    [Subject] NVARCHAR(100) NOT NULL, 
    [GroupId] INT NULL, 
    [TypeId] INT NULL, 
    [SourceId] INT NULL, 
    [StateId] INT NOT NULL, 
    [AgentId] INT NULL, 
    [PriorityId] INT NOT NULL, 
    [Description] NVARCHAR(500) NULL, 
    CONSTRAINT [PK_Tickets] PRIMARY KEY (Id),
    CONSTRAINT [FK_Tickets_Groups] FOREIGN KEY (GroupId) REFERENCES Groups(Id),
    CONSTRAINT [FK_Tickets_Types] FOREIGN KEY (TypeId) REFERENCES Types(Id),
    CONSTRAINT [FK_Tickets_Sources] FOREIGN KEY (SourceId) REFERENCES Sources(Id),
    CONSTRAINT [FK_Tickets_States] FOREIGN KEY (StateId) REFERENCES States(Id),
    CONSTRAINT [FK_Tickets_Priorities] FOREIGN KEY (PriorityId) REFERENCES Priorities(Id),
    CONSTRAINT [FK_Tickets_Users] FOREIGN KEY (AgentId) REFERENCES Users(Id),
)
